# Generated by Django 4.1.3 on 2022-11-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BookCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='BookCovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=20)),
                ('release_number', models.IntegerField()),
                ('release_date', models.DateField()),
                ('size', models.CharField(max_length=11)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isAvailable', models.BooleanField()),
                ('num_of_books_items', models.IntegerField()),
                ('number_of_pages', models.CharField(max_length=20)),
                ('avatar', models.BinaryField()),
                ('book_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.bookcategories')),
                ('book_cover_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.bookcovers')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.languages')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.publishers')),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthorships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.bookauthors')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.books')),
            ],
        ),
    ]
