# Generated by Django 4.1.3 on 2022-11-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookauthorships',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookauthorships',
            old_name='book_author_id',
            new_name='book_author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='book_category_id',
            new_name='book_category',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='book_cover_id',
            new_name='book_cover',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='isAvailable',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='num_of_books_items',
            new_name='num_of_book_items',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.AlterModelTable(
            name='bookauthors',
            table='BookAuthors',
        ),
        migrations.AlterModelTable(
            name='bookauthorships',
            table='BookAuthorships',
        ),
        migrations.AlterModelTable(
            name='bookcategories',
            table='BookCategories',
        ),
        migrations.AlterModelTable(
            name='bookcovers',
            table='BookCovers',
        ),
        migrations.AlterModelTable(
            name='books',
            table='Books',
        ),
        migrations.AlterModelTable(
            name='languages',
            table='Languages',
        ),
        migrations.AlterModelTable(
            name='publishers',
            table='Publishers',
        ),
    ]
