# Generated by Django 4.1.3 on 2022-11-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_book_id_bookauthorships_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategories',
            name='name',
            field=models.CharField(max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='bookcovers',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='release_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
