# Generated by Django 4.1.3 on 2022-11-22 21:11

import database.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_bookcategories_name_alter_bookcovers_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.books')),
            ],
            options={
                'db_table': 'BookItems',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.clients')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrdersStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'OrdersStatuses',
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=164)),
                ('tel', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'PersonalData',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', database.models.MyTypeField()),
                ('is_employee', models.BooleanField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='ReceiversData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('personal_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.personaldata')),
            ],
            options={
                'db_table': 'ReceiversData',
            },
        ),
        migrations.CreateModel(
            name='OrdersItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.bookitems')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.orders')),
            ],
            options={
                'db_table': 'OrdersItems',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.ordersstatuses'),
        ),
        migrations.AddField(
            model_name='orders',
            name='receivers_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.receiversdata'),
        ),
        migrations.AddField(
            model_name='clients',
            name='personal_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.personaldata'),
        ),
        migrations.AddField(
            model_name='clients',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.users'),
        ),
    ]
