CREATE TABLE IF NOT EXISTS `books` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) COLLATE utf8_polish_ci NOT NULL,
  `description` longtext COLLATE utf8_polish_ci NOT NULL,
  `isbn` varchar(20) COLLATE utf8_polish_ci NOT NULL,
  `release_number` int(11) NOT NULL,
  `release_date` date NOT NULL,
  `size` varchar(11) COLLATE utf8_polish_ci NOT NULL,
  `price` decimal(6,2) NOT NULL,
  `is_available` tinyint(1) NOT NULL,
  `num_of_book_items` int(11) NOT NULL,
  `number_of_pages` varchar(20) COLLATE utf8_polish_ci NOT NULL,
  `avatar` longblob,
  `book_category_id` bigint(20) NOT NULL,
  `book_cover_id` bigint(20) NOT NULL,
  `language_id` bigint(20) NOT NULL,
  `publisher_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Books_isbn_0774ed7a_uniq` (`isbn`),
  KEY `database_books_book_category_id_bedcd30f_fk_database_` (`book_category_id`),
  KEY `database_books_book_cover_id_265f41a2_fk_database_bookcovers_id` (`book_cover_id`),
  KEY `database_books_language_id_4e92e52a_fk_database_languages_id` (`language_id`),
  KEY `database_books_publisher_id_d3e22786_fk_database_publishers_id` (`publisher_id`),
  CONSTRAINT `database_books_book_category_id_bedcd30f_fk_database_` FOREIGN KEY (`book_category_id`) REFERENCES `bookcategories` (`id`),
  CONSTRAINT `database_books_book_cover_id_265f41a2_fk_database_bookcovers_id` FOREIGN KEY (`book_cover_id`) REFERENCES `bookcovers` (`id`),
  CONSTRAINT `database_books_language_id_4e92e52a_fk_database_languages_id` FOREIGN KEY (`language_id`) REFERENCES `languages` (`id`),
  CONSTRAINT `database_books_publisher_id_d3e22786_fk_database_publishers_id` FOREIGN KEY (`publisher_id`) REFERENCES `publishers` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;